# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod ‘Firebase/Core’


target 'EEG_GAE_TestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EEG_GAE_TestApp
pod ‘Firebase/Core’
  target 'EEG_GAE_TestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
